In [106]:
import numpy as np
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import fetch_mldata
from sklearn.metrics import confusion_matrix
import pickle
import gzip
from sklearn import metrics
import tensorflow as tf
import collections
import math

# Loading MNIST data

In [20]:
filename = 'mnist.pkl'
f = open(filename, 'rb')
training_data, validation_data, test_data = pickle.load(f, encoding='latin1')
f.close()

# Load USPS on Python 3.x

In [21]:
from PIL import Image
import os
import numpy as np

In [22]:
USPSMat  = []
USPSTar  = []
curPath  = 'USPSdata/Numerals'
savedImg = []

for j in range(0,10):
    curFolderPath = curPath + '/' + str(j)
    imgs =  os.listdir(curFolderPath)
    for img in imgs:
        curImg = curFolderPath + '/' + img
        if curImg[-3:] == 'png':
            img = Image.open(curImg,'r')
            img = img.resize((28, 28))
            savedImg = img
            imgdata = (255-np.array(img.getdata()))/255
            USPSMat.append(imgdata)
            USPSTar.append(j)

In [23]:
X_train = training_data[0]
Y_train = training_data[1]


X_val = validation_data[0]
Y_val = validation_data[1]

X_test = test_data[0]
Y_test = test_data[1]


# Support vector machine

In [24]:
svm = SVC(kernel='linear', C=1.0,gamma= 'auto')
#svm = SVC(kernel='rbf', C=2.0,gamma = 1)
#svm = SVC(kernel='linear', C=1.0,gamma= 'auto')
#training the model
svm.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [27]:
PredictSVM_train = []
PredictSVM_test = []
PredictSVM_val = []
PredictSVM_USPS = []



Y_test_pred = svm.predict(X_test)
Y_train_pred = svm.predict(X_train)
Y_val_pred = svm.predict(X_val)
Y_USPS_pred = svm.predict(USPSMat)

PredictSVM_test.append(Y_test_pred)
PredictSVM_USPS.append(Y_test_pred)

In [70]:
PredictSVM = np.asarray(PredictSVM).T
PredictSVM.shape

(10000, 1)

In [29]:
print("Testing Accuracy of SVM on MNIST data:",metrics.accuracy_score(Y_test, Y_test_pred))
print("Training Accuracy of SVM:",metrics.accuracy_score(Y_train, Y_train_pred))
print("Validation Accuracy of SVM:",metrics.accuracy_score(Y_val, Y_val_pred))
print("Testing Accuracy of SVM on USPS data:",metrics.accuracy_score(USPSTar, Y_USPS_pred))

Testing Accuracy of SVM on MNIST data: 0.939
Training Accuracy of SVM: 0.97246
Validation Accuracy of SVM: 0.9423
Testing Accuracy of SVM on USPS data: 0.2912645632281614


In [32]:
print("Confusion matrix of testing on USPS Data:\n",confusion_matrix(Y_USPS_pred, USPSTar)) 
print("Confusion matrix of training on MNIST Data:\n",confusion_matrix(Y_train_pred, Y_train)) 
print("Confusion matrix of validation on MNIST Data:\n",confusion_matrix(Y_val_pred, Y_val)) 

Confusion matrix of testing on USPS Data:
 [[ 348   60  139   56   24   47  146   19  100   18]
 [   0  303   63   58   24   25   19   74   16   38]
 [ 476  534 1293  341  221  652  903  201  298  204]
 [ 152  275  115  898   82  240   55  706  449  588]
 [ 222  230   33    8  800   41   86   54  126  142]
 [ 345  172  221  520  215  876  264  294  692  104]
 [  74   17   55    9   10   30  462   12   82    8]
 [ 172  351   45   45  464   35   38  522   58  580]
 [  10   37   21   48   82   41    2   84  160  155]
 [ 201   21   14   17   78   13   25   34   19  163]]
Confusion matrix of training on MNIST Data:
 [[4917    1    6    9    2   13    7    3   10    9]
 [   0 5647   15    8    8   11    1    5   37   13]
 [   1    9 4828   67    9   15    7   26   26    7]
 [   0    5   30 4893    2   87    1    6   76   18]
 [   1    0   19    1 4751    9    6   30    7   84]
 [   3    0    6   59    0 4305   16    2   56   13]
 [   4    0   14    0    4   22 4908    1    8    0]
 [   0    

# Random Forest

In [183]:
random_forest = RandomForestClassifier(n_estimators=8)
random_forest.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=8, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [184]:
PredictRF = []
PredictRF_USPS = []
Y_test_pred = random_forest.predict(X_test)
Y_train_pred = random_forest.predict(X_train)
Y_val_pred = random_forest.predict(X_val)
Y_USPS_pred = random_forest.predict(USPSMat)
PredictRF.append(Y_test_pred)
PredictRF_USPS.append(Y_USPS_pred)

In [185]:
PredictRF = np.asarray(PredictRF).T
PredictRF.shape

(10000, 1)

In [186]:
print("Testing Accuracy of Random Forest on MNIST data:",metrics.accuracy_score(Y_test, Y_test_pred))
print("Training Accuracy of Random Forest on MNIST data:",metrics.accuracy_score(Y_train, Y_train_pred))
print("Validation Accuracy of Random Forest on MNIST data:",metrics.accuracy_score(Y_val, Y_val_pred))
print("Testing Accuracy of Random Forest on USPS data:",metrics.accuracy_score(USPSTar, Y_USPS_pred))

Testing Accuracy of Random Forest on MNIST data: 0.9389
Training Accuracy of Random Forest on MNIST data: 0.99818
Validation Accuracy of Random Forest on MNIST data: 0.9456
Testing Accuracy of Random Forest on USPS data: 0.28781439071953596


In [187]:
print("Confusion matrix of testing on USPS Data:\n",confusion_matrix(Y_USPS_pred, USPSTar))
print("Confusion matrix of training on MNIST Data:\n",confusion_matrix(Y_train_pred, Y_train)) 
print("Confusion matrix of validation on MNIST Data:\n",confusion_matrix(Y_val_pred, Y_val)) 

Confusion matrix of testing on USPS Data:
 [[524  93 181 153  79 207 361  89 116  78]
 [ 85 595 172  96 276 109 109 457 142 360]
 [358 263 987 245 171 214 374 425 284 350]
 [ 92 105 140 900 118 273  96 176 284 297]
 [337  97  81 100 757 100 177  76 186 233]
 [199 128 182 302 183 864 318 220 655 145]
 [121  40  59  17  48  90 437  49 104  28]
 [105 655 160 114 281  79  75 474  59 345]
 [ 28  15  24  29  29  32  21  18 129  75]
 [151   9  13  44  58  32  32  16  41  89]]
Confusion matrix of training on MNIST Data:
 [[4932    0    1    0    1    1    0    0    1    4]
 [   0 5677    1    1    2    1    1    0    3    0]
 [   0    0 4961    8    1    1    1    3    1    1]
 [   0    0    1 5088    0    7    0    0    3    2]
 [   0    0    0    0 4852    1    1    1    1    8]
 [   0    0    0    1    0 4494    2    0    4    1]
 [   0    0    0    0    0    1 4946    0    2    0]
 [   0    0    1    0    0    0    0 5168    0    6]
 [   0    0    2    3    0    0    0    0 4827    2]
 [  

# Neural Network

In [52]:
import keras
from keras.datasets import mnist
from keras.layers import Dense
from keras.models import Sequential

In [53]:
def one_hot_vector(Y_train):
    return np.eye(10)[Y_train]

In [54]:
X_train = np.asarray(training_data[0])
Y_train = one_hot_vector(training_data[1])

X_val = np.asarray(validation_data[0])
Y_val = one_hot_vector(validation_data[1])

X_test = np.asarray(test_data[0])
Y_test = one_hot_vector(test_data[1])

X_test_USPS = np.asarray(USPSMat)
Y_test_USPS = one_hot_vector(USPSTar)

In [55]:
num_classes=10
image_vector_size=28*28
image_size = 784 

model = Sequential()
model.add(Dense(units=32, activation='sigmoid', input_shape=(image_size,)))
model.add(Dense(units=num_classes, activation='softmax'))
model.compile(optimizer='sgd', loss='categorical_crossentropy',metrics=['accuracy'])
history = model.fit(X_train, Y_train, batch_size=128, epochs=50, verbose=False,validation_split=.1)


In [56]:
loss_test_MNIST,accuracy_test_MNIST = model.evaluate(X_test, Y_test, verbose=False)
loss_train,accuracy_train = model.evaluate(X_train, Y_train, verbose=False)
loss_test_USPS,accuracy_test_USPS = model.evaluate(X_test_USPS, Y_test_USPS, verbose=False)
loss_val,accuracy_val = model.evaluate(X_val, Y_val, verbose=False)

In [86]:
PredictNN = []
PredictNN_USPS = []
Y_test_pred = model.predict(X_test)
Y_train_pred = model.predict(X_train)
Y_val_pred = model.predict(X_val)
Y_USPS_pred = model.predict(np.asarray(USPSMat))
PredictNN.append(Y_test_pred)
PredictNN_USPS.append(Y_USPS_pred)



In [90]:
PredictNN = np.asarray(PredictNN)
PredictNN.shape

(1, 10000, 10)

In [58]:
print("Accuracy of training on MNIST Data :",accuracy_train)
print("Accuracy of testing on MNIST Data :",accuracy_test_MNIST)
print("Accuracy of validation on MNIST Data :",accuracy_val)
print("Accuracy of testing on USPS Data :",accuracy_test_USPS)

Accuracy of training on MNIST Data : 0.90474
Accuracy of testing on MNIST Data : 0.9079
Accuracy of validation on MNIST Data : 0.9136
Accuracy of testing on USPS Data : 0.36071803589434415


In [59]:
X_train = training_data[0]
Y_train = training_data[1]

X_val = validation_data[0]
Y_val = validation_data[1]

X_test = test_data[0]
Y_test = test_data[1]

X_test_USPS = np.asarray(USPSMat)
Y_test_USPS = USPSTar

In [60]:
Y_USPS_testing = []
for i in range(len(Y_USPS_pred)):
    Y_USPS_testing.append(np.argmax(Y_USPS_pred[i]))
print("Confusion matrix of testing on USPS Data:\n",confusion_matrix(Y_test_USPS, Y_USPS_testing))

Y_testing = []
for i in range(len(Y_test_pred)):
    Y_testing.append(np.argmax(Y_test_pred[i]))
print("Confusion matrix of testing on MNIST Data:\n",confusion_matrix(Y_test, Y_testing))

Y_training = []
for i in range(len(Y_train_pred)):
    Y_training.append(np.argmax(Y_train_pred[i]))
print("Confusion matrix of training on MNIST Data:\n",confusion_matrix(Y_train, Y_training))

Confusion matrix of testing on USPS Data:
 [[ 598    3  318   61  296  167   67   69   98  323]
 [ 159  356  169  211  139  108   18  616  206   18]
 [ 216   19 1207  144   47  110   84   93   61   18]
 [  96    3  124 1257   12  262   18   98   91   39]
 [  44   82   35   39 1057  193   32  164  180  174]
 [ 197   17  184  196   36 1079  134   83   58   16]
 [ 438   11  343   84  103  208  709   27   53   24]
 [ 155  217  342  380   28  188   18  420  205   47]
 [ 151   29  155  186  122  762  124   55  356   60]
 [  43  176  175  403  141  113   12  498  264  175]]
Confusion matrix of testing on MNIST Data:
 [[ 956    0    4    2    0    7    9    1    1    0]
 [   0 1111    1    3    0    2    4    1   13    0]
 [  11    7  905   16   16    2   15   15   36    9]
 [   3    0   22  901    1   36    3   16   20    8]
 [   1    4    4    0  911    1   12    2    5   42]
 [  15    3    7   46    9  741   20   12   31    8]
 [  18    3    6    0   16   16  893    1    5    0]
 [   4   16

# Logistic Regression

In [157]:
def one_hot_vector(Y_train):
    return np.eye(10)[Y_train]

In [166]:
X_train = training_data[0]
Y_train = one_hot_vector(training_data[1])

X_val = validation_data[0]
Y_val = one_hot_vector(validation_data[1])

X_test = test_data[0]
Y_test = one_hot_vector(test_data[1])

X_test_USPS = np.asarray(USPSMat)
Y_test_USPS = one_hot_vector(USPSTar)

In [167]:
def softmax(ak):
    exp_ak = []
    for i in range(len(ak)):
        exp_ak.append(np.exp(ak[i]))
    sum_ak = np.sum(np.exp(ak))
    softmax_val = exp_ak/sum_ak
    return softmax_val



In [168]:
def init_weights():
    weight = np.zeros((10,784))
    return np.asarray(weight)

In [169]:
weight = init_weights()

In [170]:
def logistic_regression(x,y,eta,weight):
    for i in range(x.shape[0]):
        ak = np.dot(weight,x[i])
        pred_target = softmax(ak)
        for j in range(10):
            val = (pred_target[j] - y[i,j]) * x[i]
            weight[j] = weight[j] - eta * val    
    return weight

In [171]:
def accuracy(Data, TargetData,weight):
    ak = np.dot(Data,weight.T)
    pred = softmax(ak)
    pred_target = np.argmax(pred,axis =1)
    accuracy_val = (pred_target==TargetData).sum()/len(pred_target)
    return accuracy_val, pred_target

In [172]:
#PredictLR_train = []
#PredictLR_val = []
#PredictLR_test = []
PredictLR = []

PredictLR_USPS = []

weight_training = logistic_regression(np.asarray(X_train),np.asarray(Y_train),0.01,weight)
accuracy_training, pred_train = accuracy(X_train,training_data[1],weight_training)
PredictLR.append(pred_train)
print("Accuracy of training on MNIST data: ",accuracy_training)

weight_validation = logistic_regression(np.asarray(X_val),np.asarray(Y_val),0.01,weight)
accuracy_val, pred_val = accuracy(X_val,validation_data[1],weight_validation)
#PredictLR_val.append(pred_val)
print("Accuracy of validation on MNIST data: ",accuracy_val)

weight_test = logistic_regression(np.asarray(X_test),np.asarray(Y_test),0.01,weight)
accuracy_test, pred_test = accuracy(X_test,test_data[1],weight_test)
#PredictLR_test.append(pred_test)
print("Accuracy of testing on MNIST data: ",accuracy_test)

weight_test_USPS = logistic_regression(np.asarray(X_test_USPS),np.asarray(Y_test_USPS),0.01,weight)
accuracy_test_USPS, pred_test_USPS = accuracy(X_test_USPS,USPSTar,weight_test_USPS)
PredictLR_USPS.append(pred_test_USPS)
print("Accuracy of testing on USPS data: ",accuracy_test_USPS)

Accuracy of training on MNIST data:  0.90686
Accuracy of validation on MNIST data:  0.918
Accuracy of testing on MNIST data:  0.9244
Accuracy of testing on USPS data:  0.16495824791239563


In [153]:
len(X_test_USPS)

19999

In [173]:
X_train = training_data[0]
Y_train = training_data[1]

X_val = validation_data[0]
Y_val = validation_data[1]

X_test = test_data[0]
Y_test = test_data[1]

X_test_USPS = np.asarray(USPSMat)
Y_test_USPS = USPSTar

In [177]:
print("Confusion matrix of testing on USPS Data:\n",confusion_matrix(Y_test_USPS, pred_test_USPS))
print("Confusion matrix of testing on MNIST Data:\n",confusion_matrix(Y_test, pred_test))
print("Confusion matrix of training on MNIST Data:\n",confusion_matrix(Y_train, pred_train))
print("Confusion matrix of validation on MNIST Data:\n",confusion_matrix(Y_val, pred_val))

Confusion matrix of testing on USPS Data:
 [[  41    0    2    4    0   10   73    0    2 1868]
 [   0    8    5    1    3    1   62    2    2 1916]
 [   1    1  193   26    0    9  206    0   23 1540]
 [   0    0    0   25    0    3    6    0    1 1965]
 [   0    0    0    0    1    0   16    0    0 1983]
 [   6    1    7    2    0   33   86    0   18 1847]
 [   2    1   14    8    0    4  987    0   34  950]
 [   0    0    0    1    0    3    2    6    1 1987]
 [   1    0    0    0    0    0   14    0    5 1980]
 [   0    0    0    0    0    0    0    0    0 2000]]
Confusion matrix of testing on MNIST Data:
 [[ 945    0   11    5    0    4    8    2    5    0]
 [   0 1101    6    3    1    6    1    1   16    0]
 [   3    1  958    9   11    3   12   11   21    3]
 [   0    0   22  925    0   36    0   10   12    5]
 [   0    1    8    1  915    1    8    2    8   38]
 [   6    2   16   28   10  771    9    4   38    8]
 [   7    3   10    1    6   22  903    1    5    0]
 [   1    5

# Ensemble

In [134]:
Ensemble = []
for i in range(10000):
    Ensemble.append(PredictLR[i])
    Ensemble.append(PredictSVM[i])
    Ensemble.append(PredictRF[i])
    Ensemble.append(PredictNN[0][i])

    

In [135]:
def mode(Ensemble):
    most = max(list(map(Ensemble.count, Ensemble)))
    return list(set(filter(lambda x: Ensemble.count(x) == most, Ensemble)))

In [136]:
for i in range(len(Ensemble)):
    accuracy =  max(mode(Ensemble[i].tolist()))
print(accuracy)

0.9883993864059448
